coverage:
  status:
    project: False
    patch: False

flag_management:
  individual_flags:
    - name: anomalytics
      paths:
        - src/anomalytics/
      statuses:
        - type: project
          target: 90%
          threshold: 1%
